### PR TITLE
Fix naming of sans family

### LINKED ISSUE #21: Fix naming of sans family

### PR DESCRIPTION
**Pull request by famasoon**
Fix #21

### CODE REVIEW

**Comment by ikanago** [comment]
Thank you for your work!
But some of the test fails due to the existing build error, so I'm going to investigate it ahead of review.
I'm going to create another PR fixing the problem, merge it toward main branch and re-run CI on this PR.

**Comment by ikanago** [comment]
Build error in CI on main branch must be solved on #24 , but the same error occurs... 🤔 
The error was solved by refreshing the build cache on GitHub Actions ~~and [currently failing job](https://github.com/ikanago/omekasy/runs/6283291248?check_suite_focus=true) on this PR uses the same cached artifacts.
So I have thought everything should go well, but...~~
[Currently failing job](https://github.com/ikanago/omekasy/runs/6283291248?check_suite_focus=true) and the job succeeded on main branch uses different cache artifact.
So I have to invalidate the current cache in some way.

**Comment by ikanago** [comment]
As a workaround, stopped using cache temporarily.

File: src/convert.rs [hunk 1]
```diff
@@ -120,38 +120,38 @@ mod tests {
     }
 
     #[test]
-    fn sans_bold() {
+    fn bold_sans() {
```
Comment (ikanago) [inline src/convert.rs:123]: Small but helpful fix 👍

**Review by ikanago — APPROVED** [review]
This is just expected change.
Thank you for your contribution, famasoon 🙏
